import { Car } from "@/types/car";

export const mockCars: Car[] = [
    {
        id: "1",
        brand: "Volkswagen",
        model: "Golf",
        year: 2021,
        price_eur: 22500,
        mileage: 35000,
        fuel: "Petrol",
        gearbox: "Automatic",
        country: "Germany",
        location: "Berlin",
        images: ["https://images.unsplash.com/photo-1541899481282-d53bffe3c35d", "https://images.unsplash.com/photo-1494976388531-d1058494cdd8"],
        sourcePlatform: "Mobile.de",
        sourceUrl: "https://mobile.de/1",
    },
    {
        id: "2",
        brand: "BMW",
        model: "3 Series",
        year: 2020,
        price_eur: 31000,
        mileage: 45000,
        fuel: "Diesel",
        gearbox: "Automatic",
        country: "Poland",
        location: "Warsaw",
        images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e"],
        sourcePlatform: "Otomoto",
        sourceUrl: "https://otomoto.pl/2",
    },
    {
        id: "3",
        brand: "Audi",
        model: "A4",
        year: 2022,
        price_eur: 38500,
        mileage: 15000,
        fuel: "Hybrid",
        gearbox: "Automatic",
        country: "Romania",
        location: "Bucharest",
        images: ["https://images.unsplash.com/photo-1606152421802-db97b9c7a11b"],
        sourcePlatform: "Autovit",
        sourceUrl: "https://autovit.ro/3",
    },
    {
        id: "4",
        brand: "Mercedes-Benz",
        model: "A-Class",
        year: 2019,
        price_eur: 24000,
        mileage: 55000,
        fuel: "Petrol",
        gearbox: "Automatic",
        country: "Bulgaria",
        location: "Sofia",
        images: ["https://images.unsplash.com/photo-1511919884226-fd3cad34687c"],
        sourcePlatform: "Mobile.bg",
        sourceUrl: "https://mobile.bg/4",
    },
    {
        id: "5",
        brand: "Volvo",
        model: "XC40",
        year: 2023,
        price_eur: 42000,
        mileage: 5000,
        fuel: "Electric",
        gearbox: "Automatic",
        country: "Moldova",
        location: "Chisinau",
        images: ["https://images.unsplash.com/photo-1590362891175-3794ac1b88c3"],
        sourcePlatform: "999.md",
        sourceUrl: "https://999.md/5",
    },
];
